version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: decorator
    versions:
    - 5.0.0
    - 5.0.1
    - 5.0.2
    - 5.0.3
    - 5.0.4
    - 5.0.6
  - dependency-name: pylint
    versions:
    - 2.6.1
    - 2.7.3
    - 2.8.0
  - dependency-name: faker
    versions:
    - 6.2.0
    - 6.5.1
    - 7.0.0
  - dependency-name: importlib-metadata
    versions:
    - 3.6.0
    - 3.8.0
    - 3.8.1
    - 3.9.0
    - 3.9.1
    - 4.0.0
  - dependency-name: matplotlib
    versions:
    - 3.4.0
  - dependency-name: setuptools
    versions:
    - 54.0.0
    - 54.1.0
    - 54.1.3
  - dependency-name: s3transfer
    versions:
    - 0.3.5
  - dependency-name: celery
    versions:
    - 5.0.5
  - dependency-name: kombu
    versions:
    - 5.0.2
  - dependency-name: pillow
    versions:
    - 8.1.1
  - dependency-name: singledispatch
    versions:
    - 3.4.0.4
    - 3.5.0
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.1
  - dependency-name: cryptography
    versions:
    - 3.3.2
    - "3.4"
    - 3.4.1
    - 3.4.2
    - 3.4.3
  - dependency-name: pyzmq
    versions:
    - 22.0.0
    - 22.0.1
  - dependency-name: amqp
    versions:
    - 5.0.5
    - 5.0.6
  - dependency-name: django-waffle
    versions:
    - 2.1.0
  - dependency-name: astroid
    versions:
    - 2.5.4
    - 2.5.5
  - dependency-name: django-extensions
    versions:
    - 3.1.1.post1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
