language: python
dist: trusty
sudo: false
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install --only-binary=numpy numpy
  - pip install -r requirements.txt
python:
  - "2.7.6"
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
