language: python
dist: xenial
python:
  - "3.6"
install:
  - pip install -U pip==19.1
  - pip install -U wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
