language: python
sudo: false
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
python:
  - "2.7"
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
