db:
  image: postgres
rabbitmq:
  image: rabbitmq
web:
  image: ccnmtl/capsim
  command: /ve/bin/python manage.py runserver 0.0.0.0:8000 --settings=capsim.settings_compose
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  links:
    - db
    - rabbitmq
celery:
  image: ccnmtl/capsim
  command: /ve/bin/python manage.py celery worker --settings=capsim.settings_compose
  environment:
    - C_FORCE_ROOT=true
  volumes:
    - .:/app
  links:
    - db
    - rabbitmq
