db:
  image: postgres
rabbitmq:
  image: rabbitmq
web:
  image: ccnmtl/capsim
  environment:
    - SETTINGS=settings_compose
  command: manage runserver 0.0.0.0:8000
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  links:
    - db
    - rabbitmq
celery:
  image: ccnmtl/capsim
  command: worker
  environment:
    - C_FORCE_ROOT=true
    - SETTINGS=settings_compose    
  volumes:
    - .:/app
  links:
    - db
    - rabbitmq
