version: "3"
volumes:
  ve:
services:
  db:
    image: postgres:12.3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  rabbitmq:
    image: rabbitmq:3.8.3
    ports:
      - "5672:5672"
  web:
    image: python:3.6-stretch
    environment:
      - SETTINGS=settings_compose
      - APP=capsim
    working_dir: /app
    command: /bin/bash -c "make ./ve/sentinal && /app/docker-run.sh migrate && /app/docker-run.sh manage runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - /app/ve/
    ports:
      - "8000:8000"
  celery:
    image: python:3.6-stretch
    working_dir: /app
    command: /bin/bash -c "make ./ve/sentinal && /app/docker-run.sh worker"
    environment:
      #- C_FORCE_ROOT=true
      - SETTINGS=settings_compose 
      - APP=capsim
    volumes:
      - .:/app
      - /app/ve/
