# Generated by Django 2.2.12 on 2020-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='dependent_variable',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='independent_variable',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='status',
            field=models.CharField(default='enqueued', max_length=256),
        ),
        migrations.AlterField(
            model_name='exprun',
            name='mass',
            field=models.FloatField(default='100.0'),
        ),
        migrations.AlterField(
            model_name='exprun',
            name='status',
            field=models.CharField(default='enqueued', max_length=256),
        ),
        migrations.AlterField(
            model_name='interventionlevel',
            name='level',
            field=models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=256),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='num_type',
            field=models.CharField(choices=[('float', 'floating point'), ('int', 'integer')], max_length=256),
        ),
    ]
